version: '3'
services:

  postgres:
    # https://hub.docker.com/_/postgres
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    # https://registry.hub.docker.com/_/redis
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - "3050:80"
    depends_on:
      - client
      - api

  api:
    # server:5000 is a real address for docker
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # exclusion (do not overwrite, no access)
      - ./server:/app # redirect to server for any access to app; any changes in server folder will be reflected to app folder
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
#    expose:
#      - 5000
#    ports:
#      - "5000:5000"

  client:
    # client:3000 is a real address for docker
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
#    expose:
#      - 3000
#    ports:
#      - "3000:3000"

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
